import type { Knex } from 'knex';

/**
 * A user's own note on a saved item — "why did you save this?".
 *
 * Distinct from `caption` (the original post text that arrived with the link)
 * and from `summary` (generated by the categorizer). This one is hand-written
 * and never overwritten by enrichment.
 */
export async function up(knex: Knex): Promise<void> {
  await knex.schema.withSchema('data').alterTable('items', (table) => {
    table.text('note').nullable().comment('User-written note — why this was saved');
  });
}

export async function down(knex: Knex): Promise<void> {
  await knex.schema.withSchema('data').alterTable('items', (table) => {
    table.dropColumn('note');
  });
}
